version: 2
jobs:
  build:
    docker:
      - image: slocomptech/docker-arduino
    steps:
      - checkout
      - run:
          name: Checkout submodules
          command: git submodule sync && git submodule update --init
      - run:
          name: Build Sketch
          command: arduino-builder -hardware ${ARDUINO_HARDWARE} -tools ${ARDUINO_TOOLS}/avr -tools ${ARDUINO_TOOLS_BUILDER} -libraries ${ARDUINO_LIBS} -fqbn arduino:avr:micro src/main.cpp
